<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>WinFormApp</RootNamespace>
    <AssemblyName>RapidTDD</AssemblyName>
    <ApplicationIcon>TDD9.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <Deterministic>false</Deterministic>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DockPanelSuite" Version="3.1.1" />
    <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />

    <ProjectReference Include="..\FastColoredTextBox\FastColoredTextBox.csproj" />

    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.1" />

    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.AnalyzerUtilities" Version="3.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.9.0" />

    <PackageReference Include="Microsoft.DiaSymReader" Version="2.0.0" />

    <PackageReference Include="System.Buffers" Version="4.6.1" />
    <PackageReference Include="System.Collections.Immutable" Version="10.0.1" />
    <PackageReference Include="System.Composition" Version="10.0.1" />
    <PackageReference Include="System.IO.Pipelines" Version="10.0.1" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageReference Include="System.Reflection.Metadata" Version="10.0.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>  
    <EmbeddedResource Include="Resources\ColorThemes.txt" />

<EmbeddedResource Include="TestsView\images\No.png">
  <LogicalName>WinFormApp.TestsView.images.No.png</LogicalName>
</EmbeddedResource>
<EmbeddedResource Include="TestsView\images\Yes.png">
  <LogicalName>WinFormApp.TestsView.images.Yes.png</LogicalName>
</EmbeddedResource>
<EmbeddedResource Include="TestsView\images\exclamation 48.png">
  <LogicalName>WinFormApp.TestsView.images.exclamation 48.png</LogicalName>
</EmbeddedResource>   

    <Content Include="TDD.ico" />
  </ItemGroup>

</Project>