<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>FastColoredTextBoxNS</RootNamespace>
    <AssemblyName>FastColoredTextBox</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>AnyCPU</PlatformTarget>
   <EnableWindowsFormsAnalyzer>false</EnableWindowsFormsAnalyzer>
<NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>

</Project>
